#!/usr/bin/env bash
#
# Split last $REV_LIMIT commits to separated dirs

work_tree="/gns-rules.git"
rules_path="/gns-rules"
module_prefix='git_'

cd $work_tree

commits=`git log -n $REV_LIMIT --pretty=format:%H`

for commit in $commits; do
    module_name="$module_prefix$commit";
    module_path="$rules_path/$module_name";
    
    if [ -d $module_path ]; then
       echo "Module $module_name already exist"
       continue
    fi
    
    tmp_path="$rules_path/.$module_name"
    
    if [ -d $tmp_path ]; then
        echo "remove $tmp_path"
        rm -rf $tmp_path
    fi
    
    mkdir $tmp_path
    echo "Checkout $commit --> $tmp_path"
    git clone $work_tree $tmp_path
    cd $tmp_path
    git checkout -b version-$commit $commit
    git submodule init
    git submodule update
    
    cd $rules_path
    mv $tmp_path $module_path
done

# Clean up
(ls -t|head -n $REV_LIMIT;ls)|sort|uniq -u|xargs rm
